#!/bin/bash
#
# List tracked files locally in svn repository (inspired by git ls-files)
#
# Written by Chunyang Xu <chunyang@macports.org>
#
# Latest version can be found at
# https://svn.macports.org/repository/macports/users/chunyang/svn-ls-files/
#

function usage {
    echo "Usage - $(basename $0) [PATH]"
}

if [ $# -ne 0 ]; then
    if ! cd "$1" &> /dev/null; then
        usage ; exit 1
    fi
fi

for f in $( svn status --verbose --quiet | awk '{print $NF}' ); do
    [[ -f $f ]] && echo "$f"
done
