#!/bin/bash
#
# List tracked files locally in svn repository (inspired by git ls-files)
#
# Written by Chunyang Xu <chunyang@macports.org>
#
# Latest version can be found at
# https://svn.macports.org/repository/macports/users/chunyang/svn-ls-files/
#

function usage {
    echo "Usage - $0 [PATH]"
}

if [ $# -ne 0 ]
then
    cd "$1" &> /dev/null || usage
fi

for f in  $( svn status --quiet --verbose | awk '{ print $4 }' )
do
    if [ -f "$f" ]
    then
        echo "$f"
    fi
done
